<a href="https://colab.research.google.com/github/LeVargas97/LeoCode/blob/main/Atividade_1_aula_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

In [43]:
temperaturas = np.array([
  [22,24,19,21,23,20,25],
  [28,29,31,27,26,30,28],
  [19,20,18,22,21,23,24],
  [25,27,29,28,26,30,31]
  ])
print("temperatura das 4 semana é: \n" ,temperaturas)

temperatura das 4 semana é: 
 [[22 24 19 21 23 20 25]
 [28 29 31 27 26 30 28]
 [19 20 18 22 21 23 24]
 [25 27 29 28 26 30 31]]


In [56]:
for i in range(temperaturas.shape[0]):
  semana = temperaturas[i, :]
  media_semana = np.mean(semana)
  max_semana = np.max(semana)
  min_semana = np.min(semana)
  print(f"Semana {i+1}: Média = {media_semana:}, Máxima = {max_semana}, Mínima = {min_semana}")

Semana 1: Média = 22.0, Máxima = 25, Mínima = 19
Semana 2: Média = 28.428571428571427, Máxima = 31, Mínima = 26
Semana 3: Média = 21.0, Máxima = 24, Mínima = 18
Semana 4: Média = 28.0, Máxima = 31, Mínima = 25


In [49]:
tempMaxima = np.max(temperaturas)
tempMinima = np.min(temperaturas)

print("Temperatura maxima da semana é: ", tempMaxima)
print("Temperatura minima da semana é: ", tempMinima)

Temperatura maxima da semana é:  31
Temperatura minima da semana é:  18


In [51]:
filtro = (temperaturas < 20) | (temperaturas > 30)
#print(filtro)

temperaturas2 = temperaturas[filtro]
print(temperaturas2)

[19 31 19 18 31]


In [52]:
temperaturas_ajustada = np.where(temperaturas < 25, temperaturas * 1.05, temperaturas * 0.97)

print("Temperaturas ajustadas:\n", temperaturas_ajustada)


Temperaturas ajustadas:
 [[23.1  25.2  19.95 22.05 24.15 21.   24.25]
 [27.16 28.13 30.07 26.19 25.22 29.1  27.16]
 [19.95 21.   18.9  23.1  22.05 24.15 25.2 ]
 [24.25 26.19 28.13 27.16 25.22 29.1  30.07]]


In [55]:
media = np.mean(temperaturas)
print("Média das temperaturas:", media)


desvio_padrao = np.std(temperaturas)
print("Desvio padrão das temperaturas:", desvio_padrao)


mediana = np.median(temperaturas)
print("Mediana das temperaturas:", mediana)


q1 = np.percentile(temperaturas, 25)
q3 = np.percentile(temperaturas, 75)

iqr = q3 - q1

print("Intervalo interquartil das temperaturas:", iqr)


Média das temperaturas: 24.857142857142858
Desvio padrão das temperaturas: 3.8795644611429343
Mediana das temperaturas: 25.0
Intervalo interquartil das temperaturas: 6.25
