<a href="https://colab.research.google.com/github/LeVargas97/LeoCode/blob/main/Aula_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Array unidimensional
arr1 = np.array([1, 2, 3, 4, 5])


In [ ]:
print(arr1)

[1 2 3 4 5]


In [ ]:
#Array bidimensional
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Array tipado
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float16)

In [ ]:
print(arr3)

[1. 2. 3. 4. 5.]


In [ ]:
#Array de zeros feito para Inicializar variáveis em simulações ou cálculos que precisam de um ponto de partida neutro.
arr_zeros = np.zeros((2, 3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_ones = np.ones((3, 2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr_random = np.random.rand(2, 3)
print(arr_random)

[[0.4746691  0.61377441 0.91928683]
 [0.47116571 0.9575876  0.35815285]]


In [ ]:
#Multiplicação de arrays
arr_matrix_mult = np.dot(arr2, arr2.T)